---
title: "Styling Nodes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Styling Nodes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(reactflow)
nodes <- list(
  list(id = "1", position = list(x = 0, y = 0), data = list(label = "1"), type = "input"),
  list(id = "2", position = list(x = 50, y = 100), data = list(label = "2")),
  list(id = "3", position = list(x = 100, y = 200), data = list(label = "3"), type = "output")
)
edges <- list(
  list(id = "e1-2", source = "1", target = "2", type = "straight"),
  list(id = "e2-3", source = "2", target = "3", type = "smoothstep", label = "A", 
       animated = TRUE),
  list(id = "e1-3", source = "1", target = "3", type = "bezier")
)

reactflow(
  nodes = nodes,
  edges = edges,
  background(variant = "dots", gap = 12, size = 2)
)
```


[ ] Basic types
[ ] colors and formatting: via direct styling, via classes
[ ] HTML nodes
[ ] styling selected one


## Custom Nodes

```{r}
nodes <- list(
  list(id = "jd", position = list(x = 200, y = 50),
       data = list(label = "Jane Doe", title = "CEO", icon = "👩")),
  list(id = "tw", position = list(x = 0, y = 200),
       data = list(label = "Tyler Weary", title = "Designer", icon = "👨")),
  list(id = "kp", position = list(x = 400, y = 200),
       data = list(label = "Kristi Price", title = "Developer", icon = "👩"))
)
edges <- list(
  list(id = "jd-tw", source = "jd", target = "tw"),
  list(id = "jd-kp", source = "jd", target = "kp")
)


node_types <- JS(reactR::babel_transform('
import React, { memo } from "react";
import { Handle, Position } from "@xyflow/react";
 
function CustomNode({ data }) {
  return (
    <div className="container">
        <div className="emoji">
          {data.emoji}
        </div>
        <div className="text-element">
          <div className="text-name">{data.name}</div>
          <div className="text-job">{data.job}</div>
        </div>
      </div>
 
      <Handle
        type="target"
        position={Position.Top}
        className="handle"
      />
      <Handle
        type="source"
        position={Position.Bottom}
        className="handle"
      />
    </div>
  );
}
'))

reactflow(
  nodes,
  edges,
  mini_map(),
  controls(),
  background(),
  nodeTypes = node_types
)
```


